### ISSUE TITLE
[](url)

### ISSUE THREAD

**Issue by Agingvollkkaa99** [privacysandbox/topics-android#15]
[](url)

_Originally posted by @Agingvollkkaa99 in https://github.com/privacysandbox/topics-android/issues/13#issuecomment-2282794142_

**Comment by Sarrac3873** [comment]
>               [](url)
> 
> _Originally posted by @Agingvollkkaa99 in https://github.com/privacysandbox/topics-android/issues/13#issuecomment-2282794142_
>
